# 기본 import

In [33]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
pd.options.display.max_columns = 23

# 표들을 불러오기

In [34]:
sample_submission_V2 = pd.read_csv('./pubg-finish-placement-prediction/sample_submission_V2.csv')
test_V2 = pd.read_csv('./pubg-finish-placement-prediction/test_V2.csv')
train_V2 = pd.read_csv('./pubg-finish-placement-prediction/train_V2.csv')

In [35]:
sample_submission_V2

                     Id  winPlacePerc
0        9329eb41e215eb             1
1        639bd0dcd7bda8             1
2        63d5c8ef8dfe91             1
3        cf5b81422591d1             1
4        ee6a295187ba21             1
...                 ...           ...
1934169  a316c3a13887d5             1
1934170  5312146b27d875             1
1934171  fc8818b5b32ad3             1
1934172  a0f91e35f8458f             1
1934173  3696fc9f3a42b2             1

[1934174 rows x 2 columns]

In [36]:
test_V2

,Id,groupId,matchId,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,killPoints,...,numGroups,rankPoints,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints
0,9329eb41e215eb,676b23c24e70d6,45b576ab7daa7f,0,0,51.46,0,0,0,73,0,...,28,1500,0,0.0,0,0.000,0,0,588.00,1,0
1,639bd0dcd7bda8,430933124148dd,42a9a0b906c928,0,4,179.10,0,0,2,11,0,...,47,1503,2,4669.0,0,0.000,0,0,2017.00,6,0
2,63d5c8ef8dfe91,0b45f5db20ba99,87e7e4477a048e,1,0,23.40,0,0,4,49,0,...,27,1565,0,0.0,0,0.000,0,0,787.80,4,0
3,cf5b81422591d1,b7497dbdc77f4a,1b9a94f1af67f1,0,0,65.52,0,0,0,54,0,...,44,1465,0,0.0,0,0.000,0,0,1812.00,3,0
4,ee6a295187ba21,6604ce20a1d230,40754a93016066,0,4,330.20,1,2,1,7,0,...,27,1480,1,0.0,0,0.000,0,0,2963.00,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1934169,a316c3a13887d5,80e82180c90951,f276da5fd73536,1,2,381.00,3,0,7,4,1294,...,20,-1,1,0.0,0,0.000,0,0,1799.00,5,1526
1934170,5312146b27d875,147264a127c56e,fb77cbfe094a6b,0,0,0.00,0,0,0,64,1449,...,26,-1,0,0.0,0,0.000,0,0,1195.00,3,1496
1934171,fc8818b5b32ad3,7bbb4779ebedd5,efb74d5f6e9779,0,0,91.96,0,0,3,24,0,...,29,1482,0,0.0,0,7.798,1,0,3327.00,3,0
1934172,a0f91e35f8458f,149a506a64c2b1,3a2cf335bc302f,1,2,138.60,0,0,12,25,0,...,48,1456,1,0.0,0,0.000,0,0,1893.00,4,0
1934173,3696fc9f3a42b2,c770d7feaf020f,9d4e2b6d506fd0,0,0,19.80,0,0,0,86,1380,...,27,-1,0,0.0,0,0.000,0,0,68.89,0,1551

# 전처리

In [37]:
#유일한 NaN이 있는 row를 제거
Dwait = train_V2[train_V2['winPlacePerc'].notnull()]
Dwait

,Id,groupId,matchId,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,killPoints,...,rankPoints,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc
0,7f96b2f878858a,4d4b580de459be,a10357fd1a4a91,0,0,0.00,0,0,0,60,1241,...,-1,0,0.0000,0,0.000,0,0,244.80,1,1466,0.4444
1,eef90569b9d03c,684d5656442f9e,aeb375fc57110c,0,0,91.47,0,0,0,57,0,...,1484,0,0.0045,0,11.040,0,0,1434.00,5,0,0.6400
2,1eaf90ac73de72,6a4a42c3245a74,110163d8bb94ae,1,0,68.00,0,0,0,47,0,...,1491,0,0.0000,0,0.000,0,0,161.80,2,0,0.7755
3,4616d365dd2853,a930a9c79cd721,f1f1f4ef412d7e,0,0,32.90,0,0,0,75,0,...,1408,0,0.0000,0,0.000,0,0,202.70,3,0,0.1667
4,315c96c26c9aac,de04010b3458dd,6dc8ff871e21e6,0,0,100.00,0,0,0,45,0,...,1560,0,0.0000,0,0.000,0,0,49.75,2,0,0.1875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4446961,afff7f652dbc10,d238e426f50de7,18492834ce5635,0,0,0.00,0,0,0,74,1029,...,-1,0,1292.0000,0,0.000,0,0,1019.00,3,1507,0.1786
4446962,f4197cf374e6c0,408cdb5c46b2ac,ee854b837376d9,0,1,44.15,0,0,0,69,0,...,1501,0,0.0000,0,0.000,0,0,81.70,6,0,0.2935
4446963,e1948b1295c88a,e26ac84bdf7cef,6d0cd12784f1ab,0,0,59.06,0,0,0,66,0,...,1500,0,0.0000,0,2.184,0,0,788.70,4,0,0.4815
4446964,cc032cdd73b7ac,c2223f35411394,c9c701d0ad758a,0,4,180.40,1,1,2,11,0,...,1418,2,0.0000,0,0.000,0,0,2748.00,8,0,0.8000
4446965,0d8e7ed728b6fd,8c74f72fedf5ff,62a16aabcc095c,0,2,268.00,0,0,1,18,0,...,1590,0,1369.0000,0,0.000,0,0,1244.00,5,0,0.5464

In [38]:
# 쓸데없는 column 제거
Dtrain = Dwait.drop(['Id', 'groupId', 'matchId', 'killPoints', 'rankPoints', 'winPoints'], axis=1)
Dtrain

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,kills,killStreaks,longestKill,matchDuration,matchType,maxPlace,numGroups,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPlacePerc
0,0,0,0.00,0,0,0,60,0,0,0.00,1306,squad-fpp,28,26,0,0.0000,0,0.000,0,0,244.80,1,0.4444
1,0,0,91.47,0,0,0,57,0,0,0.00,1777,squad-fpp,26,25,0,0.0045,0,11.040,0,0,1434.00,5,0.6400
2,1,0,68.00,0,0,0,47,0,0,0.00,1318,duo,50,47,0,0.0000,0,0.000,0,0,161.80,2,0.7755
3,0,0,32.90,0,0,0,75,0,0,0.00,1436,squad-fpp,31,30,0,0.0000,0,0.000,0,0,202.70,3,0.1667
4,0,0,100.00,0,0,0,45,1,1,58.53,1424,solo-fpp,97,95,0,0.0000,0,0.000,0,0,49.75,2,0.1875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4446961,0,0,0.00,0,0,0,74,0,0,0.00,1873,squad-fpp,29,28,0,1292.0000,0,0.000,0,0,1019.00,3,0.1786
4446962,0,1,44.15,0,0,0,69,0,0,0.00,1435,solo,93,93,0,0.0000,0,0.000,0,0,81.70,6,0.2935
4446963,0,0,59.06,0,0,0,66,0,0,0.00,1321,squad-fpp,28,28,0,0.0000,0,2.184,0,0,788.70,4,0.4815
4446964,0,4,180.40,1,1,2,11,2,1,98.50,1373,squad-fpp,26,25,2,0.0000,0,0.000,0,0,2748.00,8,0.8000
4446965,0,2,268.00,0,0,1,18,2,1,78.25,1766,solo-fpp,98,94,0,1369.0000,0,0.000,0,0,1244.00,5,0.5464

In [39]:
#도보 이동 없이 무기 획득 3개 이상이라면 불법으로 판단
((Dtrain['walkDistance'] == 0) & (Dtrain['weaponsAcquired'] > 2)).sum()

5768

In [40]:
#rideDistance가 0인데 roadKills가 1 이상이라면?
((Dtrain['rideDistance'] == 0) & (Dtrain['roadKills'] > 0)).sum()

186

In [41]:
#다행이다
((Dtrain['matchType'].str.contains('solo')) & (Dtrain['revives'] > 0)).sum()

0

In [42]:
# boosts랑 heals가 item 기반이므로 도보 이동 없이 무기 획득 3개 이상이랑 같음
print(((Dtrain['walkDistance'] == 0) & (Dtrain['boosts'] > 2)).sum())
print(((Dtrain['walkDistance'] == 0) & (Dtrain['heals'] > 2)).sum())

118
492

In [43]:
pencil_a = (Dtrain[(Dtrain['walkDistance'] == 0) & ((Dtrain['weaponsAcquired'] > 2) | (Dtrain['boosts'] > 2) | (Dtrain['heals'] > 2))].index)
Dtrain_a = Dtrain.drop(pencil_a)

In [44]:
#matchType 각각의 개수
Dtrain_a['matchType'].value_counts()

squad-fpp           1756185
duo-fpp              996688
squad                626525
solo-fpp             536753
duo                  313591
solo                 177753
normal-squad-fpp      15996
crashfpp               6287
normal-duo-fpp         5406
flaretpp               2505
normal-solo-fpp        1490
flarefpp                718
normal-squad            439
crashtpp                371
normal-solo             277
normal-duo              191
Name: matchType, dtype: int64

In [45]:
Dtrain_b = Dtrain_a.copy()
Dtrain_b['winPlacePerc'] = round(Dtrain_a['winPlacePerc'] * 10)
Dtrain_b
# so winPlacePerc가 0에 가까울수록 1등 확률 낮고, 10에 가까울수록 1등 확률 높다.

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,kills,killStreaks,longestKill,matchDuration,matchType,maxPlace,numGroups,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPlacePerc
0,0,0,0.00,0,0,0,60,0,0,0.00,1306,squad-fpp,28,26,0,0.0000,0,0.000,0,0,244.80,1,4.0
1,0,0,91.47,0,0,0,57,0,0,0.00,1777,squad-fpp,26,25,0,0.0045,0,11.040,0,0,1434.00,5,6.0
2,1,0,68.00,0,0,0,47,0,0,0.00,1318,duo,50,47,0,0.0000,0,0.000,0,0,161.80,2,8.0
3,0,0,32.90,0,0,0,75,0,0,0.00,1436,squad-fpp,31,30,0,0.0000,0,0.000,0,0,202.70,3,2.0
4,0,0,100.00,0,0,0,45,1,1,58.53,1424,solo-fpp,97,95,0,0.0000,0,0.000,0,0,49.75,2,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4446961,0,0,0.00,0,0,0,74,0,0,0.00,1873,squad-fpp,29,28,0,1292.0000,0,0.000,0,0,1019.00,3,2.0
4446962,0,1,44.15,0,0,0,69,0,0,0.00,1435,solo,93,93,0,0.0000,0,0.000,0,0,81.70,6,3.0
4446963,0,0,59.06,0,0,0,66,0,0,0.00,1321,squad-fpp,28,28,0,0.0000,0,2.184,0,0,788.70,4,5.0
4446964,0,4,180.40,1,1,2,11,2,1,98.50,1373,squad-fpp,26,25,2,0.0000,0,0.000,0,0,2748.00,8,8.0
4446965,0,2,268.00,0,0,1,18,2,1,78.25,1766,solo-fpp,98,94,0,1369.0000,0,0.000,0,0,1244.00,5,5.0

### 다음과 같이 분류
- train_V2, test_V2, sample_submission_V2 : 날 것
- Dwait : train_V2에서 유일한 NaN을 가진 row 제거
- Dtrain : Dwait에서 Id 3총사, Points 3총사 column을 제거
- Dtrain_a : Dtrain에서 (walkDistance == 0) & ((weaponsAcquired > 2) | (boosts > 2) | (heals > 2))인 모든 row를 제거
- Dtrain_b : Dtrain_a에서  winPlacePerc 모든 원소 10배 후 소수 첫 자리에서 반올림
- train_OHE : Dtrain_b에서 One-Hot Encoding(matchType에 대해). squad / duo / solo 그리고 fpp 여부와 나머지 것들 => 7가지
- train_droped_OHE : train_OHE에서 이상치가 포함된 row 제거
- train_OHE_a : train_OHE의 winPlacePerc가 원래 값(0이상 1이하 실수)
- train_droped_OHE_a : train_droped_OHE의 winPlacePerc가 원래 값(0이상 1이하 실수)

In [68]:
Dtrain_sub = Dtrain_b.copy()
for i in Dtrain_a['matchType'].unique()[6:]:
    Dtrain_sub = Dtrain_sub.replace({'matchType':{i:'others'}})
train_OHE = pd.get_dummies(Dtrain_sub, columns=["matchType"])
train_OHE

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,kills,killStreaks,longestKill,matchDuration,...,vehicleDestroys,walkDistance,weaponsAcquired,winPlacePerc,matchType_duo,matchType_duo-fpp,matchType_others,matchType_solo,matchType_solo-fpp,matchType_squad,matchType_squad-fpp
0,0,0,0.00,0,0,0,60,0,0,0.00,1306,...,0,244.80,1,4.0,0,0,0,0,0,0,1
1,0,0,91.47,0,0,0,57,0,0,0.00,1777,...,0,1434.00,5,6.0,0,0,0,0,0,0,1
2,1,0,68.00,0,0,0,47,0,0,0.00,1318,...,0,161.80,2,8.0,1,0,0,0,0,0,0
3,0,0,32.90,0,0,0,75,0,0,0.00,1436,...,0,202.70,3,2.0,0,0,0,0,0,0,1
4,0,0,100.00,0,0,0,45,1,1,58.53,1424,...,0,49.75,2,2.0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4446961,0,0,0.00,0,0,0,74,0,0,0.00,1873,...,0,1019.00,3,2.0,0,0,0,0,0,0,1
4446962,0,1,44.15,0,0,0,69,0,0,0.00,1435,...,0,81.70,6,3.0,0,0,0,1,0,0,0
4446963,0,0,59.06,0,0,0,66,0,0,0.00,1321,...,0,788.70,4,5.0,0,0,0,0,0,0,1
4446964,0,4,180.40,1,1,2,11,2,1,98.50,1373,...,0,2748.00,8,8.0,0,0,0,0,0,0,1
4446965,0,2,268.00,0,0,1,18,2,1,78.25,1766,...,0,1244.00,5,5.0,0,0,0,0,1,0,0

In [99]:
Dtrain_sub_a = Dtrain_a.copy()
for i in Dtrain_a['matchType'].unique()[6:]:
    Dtrain_sub_a = Dtrain_sub_a.replace({'matchType':{i:'others'}})
train_OHE_a = pd.get_dummies(Dtrain_sub_a, columns=["matchType"])
train_OHE_a

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,kills,killStreaks,longestKill,matchDuration,...,vehicleDestroys,walkDistance,weaponsAcquired,winPlacePerc,matchType_duo,matchType_duo-fpp,matchType_others,matchType_solo,matchType_solo-fpp,matchType_squad,matchType_squad-fpp
0,0,0,0.00,0,0,0,60,0,0,0.00,1306,...,0,244.80,1,0.4444,0,0,0,0,0,0,1
1,0,0,91.47,0,0,0,57,0,0,0.00,1777,...,0,1434.00,5,0.6400,0,0,0,0,0,0,1
2,1,0,68.00,0,0,0,47,0,0,0.00,1318,...,0,161.80,2,0.7755,1,0,0,0,0,0,0
3,0,0,32.90,0,0,0,75,0,0,0.00,1436,...,0,202.70,3,0.1667,0,0,0,0,0,0,1
4,0,0,100.00,0,0,0,45,1,1,58.53,1424,...,0,49.75,2,0.1875,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4446961,0,0,0.00,0,0,0,74,0,0,0.00,1873,...,0,1019.00,3,0.1786,0,0,0,0,0,0,1
4446962,0,1,44.15,0,0,0,69,0,0,0.00,1435,...,0,81.70,6,0.2935,0,0,0,1,0,0,0
4446963,0,0,59.06,0,0,0,66,0,0,0.00,1321,...,0,788.70,4,0.4815,0,0,0,0,0,0,1
4446964,0,4,180.40,1,1,2,11,2,1,98.50,1373,...,0,2748.00,8,0.8000,0,0,0,0,0,0,1
4446965,0,2,268.00,0,0,1,18,2,1,78.25,1766,...,0,1244.00,5,0.5464,0,0,0,0,1,0,0

In [86]:
#이상치라고 생각된다.
print((train_OHE['weaponsAcquired'] > 12).sum())
print((train_OHE['boosts'] > 8).sum())
print((train_OHE['heals'] > 11).sum())
print((train_OHE['kills'] > 9).sum())
print((train_OHE['headshotKills'] > 3).sum())

14263
15550
56379
12688
16633

In [87]:
pencil_b = (train_OHE[(train_OHE['weaponsAcquired'] > 12) | 
                     (train_OHE['boosts'] > 8) | 
                     (train_OHE['heals'] > 11) | 
                     (train_OHE['kills'] > 9) | 
                     (train_OHE['headshotKills'] > 3)].index)
train_droped_OHE = train_OHE.drop(pencil_b)

In [100]:
pencil_c = (train_OHE_a[(train_OHE_a['weaponsAcquired'] > 12) | 
                     (train_OHE_a['boosts'] > 8) | 
                     (train_OHE_a['heals'] > 11) | 
                     (train_OHE_a['kills'] > 9) | 
                     (train_OHE_a['headshotKills'] > 3)].index)
train_droped_OHE_a = train_OHE_a.drop(pencil_c)

In [88]:
train_droped_OHE

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,kills,killStreaks,longestKill,matchDuration,...,vehicleDestroys,walkDistance,weaponsAcquired,winPlacePerc,matchType_duo,matchType_duo-fpp,matchType_others,matchType_solo,matchType_solo-fpp,matchType_squad,matchType_squad-fpp
0,0,0,0.00,0,0,0,60,0,0,0.00,1306,...,0,244.80,1,4.0,0,0,0,0,0,0,1
1,0,0,91.47,0,0,0,57,0,0,0.00,1777,...,0,1434.00,5,6.0,0,0,0,0,0,0,1
2,1,0,68.00,0,0,0,47,0,0,0.00,1318,...,0,161.80,2,8.0,1,0,0,0,0,0,0
3,0,0,32.90,0,0,0,75,0,0,0.00,1436,...,0,202.70,3,2.0,0,0,0,0,0,0,1
4,0,0,100.00,0,0,0,45,1,1,58.53,1424,...,0,49.75,2,2.0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4446961,0,0,0.00,0,0,0,74,0,0,0.00,1873,...,0,1019.00,3,2.0,0,0,0,0,0,0,1
4446962,0,1,44.15,0,0,0,69,0,0,0.00,1435,...,0,81.70,6,3.0,0,0,0,1,0,0,0
4446963,0,0,59.06,0,0,0,66,0,0,0.00,1321,...,0,788.70,4,5.0,0,0,0,0,0,0,1
4446964,0,4,180.40,1,1,2,11,2,1,98.50,1373,...,0,2748.00,8,8.0,0,0,0,0,0,0,1
4446965,0,2,268.00,0,0,1,18,2,1,78.25,1766,...,0,1244.00,5,5.0,0,0,0,0,1,0,0

In [101]:
train_droped_OHE_a

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,kills,killStreaks,longestKill,matchDuration,...,vehicleDestroys,walkDistance,weaponsAcquired,winPlacePerc,matchType_duo,matchType_duo-fpp,matchType_others,matchType_solo,matchType_solo-fpp,matchType_squad,matchType_squad-fpp
0,0,0,0.00,0,0,0,60,0,0,0.00,1306,...,0,244.80,1,0.4444,0,0,0,0,0,0,1
1,0,0,91.47,0,0,0,57,0,0,0.00,1777,...,0,1434.00,5,0.6400,0,0,0,0,0,0,1
2,1,0,68.00,0,0,0,47,0,0,0.00,1318,...,0,161.80,2,0.7755,1,0,0,0,0,0,0
3,0,0,32.90,0,0,0,75,0,0,0.00,1436,...,0,202.70,3,0.1667,0,0,0,0,0,0,1
4,0,0,100.00,0,0,0,45,1,1,58.53,1424,...,0,49.75,2,0.1875,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4446961,0,0,0.00,0,0,0,74,0,0,0.00,1873,...,0,1019.00,3,0.1786,0,0,0,0,0,0,1
4446962,0,1,44.15,0,0,0,69,0,0,0.00,1435,...,0,81.70,6,0.2935,0,0,0,1,0,0,0
4446963,0,0,59.06,0,0,0,66,0,0,0.00,1321,...,0,788.70,4,0.4815,0,0,0,0,0,0,1
4446964,0,4,180.40,1,1,2,11,2,1,98.50,1373,...,0,2748.00,8,0.8000,0,0,0,0,0,0,1
4446965,0,2,268.00,0,0,1,18,2,1,78.25,1766,...,0,1244.00,5,0.5464,0,0,0,0,1,0,0

## 머신러닝 점수 체크(최종 단계)

In [102]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [106]:
feature = train_droped_OHE_a[['matchType_duo', 'matchType_duo-fpp', 'matchType_others', 'matchType_solo',
                             'matchType_solo-fpp', 'matchType_squad', 'matchType_squad-fpp',
                             'walkDistance', 'boosts', 'heals', 'kills']]
target = train_droped_OHE_a["winPlacePerc"]

model = LinearRegression().fit(feature, target)

pred = model.predict(feature)
mae = np.round(mean_absolute_error(target, pred), 2)
mae

0.13

In [107]:
sm_feature = sm.add_constant(feature)

model = sm.OLS(target, sm_feature).fit()

print(model.summary2())

                   Results: Ordinary least squares
======================================================================
Model:              OLS              Adj. R-squared:     0.698
Dependent Variable: winPlacePerc     AIC:                -3191578.9339
Date:               2022-06-13 15:26 BIC:                -3191432.8199
No. Observations:   4338718          Log-Likelihood:     1.5958e+06
Df Model:           10               F-statistic:        1.001e+06
Df Residuals:       4338707          Prob (F-statistic): 0.00
R-squared:          0.698            Scale:              0.028058
----------------------------------------------------------------------
                      Coef.  Std.Err.     t     P>|t|   [0.025  0.975]
----------------------------------------------------------------------
const                 0.1901   0.0002 1148.7662 0.0000  0.1898  0.1905
matchType_duo         0.0395   0.0003  130.7715 0.0000  0.0389  0.0401
matchType_duo-fpp     0.0475   0.0002  226.3781 0.0000  0.0470  0.0479
matchType_others     -0.0300   0.0009  -33.6301 0.0000 -0.0318 -0.0283
matchType_solo        0.0626   0.0004  165.1437 0.0000  0.0619  0.0634
matchType_solo-fpp    0.0851   0.0003  340.0625 0.0000  0.0846  0.0855
matchType_squad      -0.0165   0.0002  -68.8747 0.0000 -0.0169 -0.0160
matchType_squad-fpp   0.0020   0.0002   10.7927 0.0000  0.0016  0.0024
walkDistance          0.0002   0.0000 1945.9554 0.0000  0.0002  0.0002
boosts                0.0253   0.0001  332.1440 0.0000  0.0251  0.0254
heals                 0.0073   0.0000  153.6214 0.0000  0.0072  0.0074
kills                 0.0180   0.0001  260.4505 0.0000  0.0179  0.0182
----------------------------------------------------------------------
Omnibus:           315667.128    Durbin-Watson:       2.000
Prob(Omnibus):     0.000         Jarque-Bera (JB):    834193.102
Skew:              0.420         Prob(JB):            0.000
Kurtosis:          4.977         Condition No.:       2272376687439192
======================================================================
* The condition number is large (2e+15). This might indicate
strong multicollinearity or other numerical problems.

In [108]:
feature = train_droped_OHE_a[['matchType_duo', 'matchType_duo-fpp', 'matchType_others', 'matchType_solo',
                             'matchType_solo-fpp', 'matchType_squad', 'matchType_squad-fpp',
                             'walkDistance', 'boosts', 'heals', 'kills']]
pd.DataFrame({
    "feature": feature.columns,
    "VIF": [variance_inflation_factor(feature.values, idx)
            for idx in range(feature.shape[1])]
})

                feature       VIF
0         matchType_duo  1.068836
1     matchType_duo-fpp  1.218317
2      matchType_others  1.009907
3        matchType_solo  1.031645
4    matchType_solo-fpp  1.090595
5       matchType_squad  1.165299
6   matchType_squad-fpp  1.464484
7          walkDistance  1.763295
8                boosts  2.251116
9                 heals  1.504188
10                kills  1.359449

In [109]:
feature = train_droped_OHE_a[['matchType_duo', 'matchType_duo-fpp', 'matchType_others', 'matchType_solo',
                             'matchType_solo-fpp', 'matchType_squad', 'matchType_squad-fpp',
                             'walkDistance', 'heals', 'kills']]
pd.DataFrame({
    "feature": feature.columns,
    "VIF": [variance_inflation_factor(feature.values, idx)
            for idx in range(feature.shape[1])]
})

               feature       VIF
0        matchType_duo  1.068499
1    matchType_duo-fpp  1.215723
2     matchType_others  1.009886
3       matchType_solo  1.031645
4   matchType_solo-fpp  1.090591
5      matchType_squad  1.163403
6  matchType_squad-fpp  1.453872
7         walkDistance  1.363931
8                heals  1.314390
9                kills  1.226061

In [110]:
feature = train_droped_OHE_a[['matchType_duo', 'matchType_duo-fpp', 'matchType_others', 'matchType_solo',
                             'matchType_solo-fpp', 'matchType_squad', 'matchType_squad-fpp',
                             'walkDistance', 'heals', 'kills']]
target = train_droped_OHE_a["winPlacePerc"]

sm_feature = sm.add_constant(feature)

model = sm.OLS(target, sm_feature).fit()

print(model.summary2())

                   Results: Ordinary least squares
======================================================================
Model:              OLS              Adj. R-squared:     0.690
Dependent Variable: winPlacePerc     AIC:                -3082640.2252
Date:               2022-06-13 15:28 BIC:                -3082507.3943
No. Observations:   4338718          Log-Likelihood:     1.5413e+06
Df Model:           9                F-statistic:        1.072e+06
Df Residuals:       4338708          Prob (F-statistic): 0.00
R-squared:          0.690            Scale:              0.028771
----------------------------------------------------------------------
                      Coef.  Std.Err.     t     P>|t|   [0.025  0.975]
----------------------------------------------------------------------
const                 0.1888   0.0002 1126.9167 0.0000  0.1885  0.1892
matchType_duo         0.0389   0.0003  127.3991 0.0000  0.0383  0.0395
matchType_duo-fpp     0.0459   0.0002  216.2944 0.0000  0.0455  0.0463
matchType_others     -0.0272   0.0009  -30.0722 0.0000 -0.0289 -0.0254
matchType_solo        0.0639   0.0004  166.4831 0.0000  0.0632  0.0647
matchType_solo-fpp    0.0865   0.0003  341.7017 0.0000  0.0860  0.0870
matchType_squad      -0.0182   0.0002  -75.4212 0.0000 -0.0187 -0.0178
matchType_squad-fpp  -0.0010   0.0002   -5.5123 0.0000 -0.0014 -0.0007
walkDistance          0.0002   0.0000 2362.4619 0.0000  0.0002  0.0002
heals                 0.0128   0.0000  286.9285 0.0000  0.0127  0.0129
kills                 0.0253   0.0001  379.0182 0.0000  0.0251  0.0254
----------------------------------------------------------------------
Omnibus:           311563.200    Durbin-Watson:       2.000
Prob(Omnibus):     0.000         Jarque-Bera (JB):    999437.880
Skew:              0.351         Prob(JB):            0.000
Kurtosis:          5.244         Condition No.:       2272542334959822
======================================================================
* The condition number is large (2e+15). This might indicate
strong multicollinearity or other numerical problems.

In [111]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

In [112]:
feature = train_droped_OHE_a[['matchType_duo', 'matchType_duo-fpp', 'matchType_others', 'matchType_solo',
                             'matchType_solo-fpp', 'matchType_squad', 'matchType_squad-fpp',
                             'walkDistance', 'heals', 'kills', 'boosts']]
target = train_droped_OHE_a["winPlacePerc"]

train_x, test_x, train_y, test_y = train_test_split(feature, target, test_size=0.3, random_state=0)

train_x, X_val, train_y, y_val = train_test_split(train_x, train_y, test_size=0.25, random_state=0)

In [113]:
reg1 = Lasso()
reg2 = Ridge()

reg1.fit(train_x, train_y)
reg2.fit(train_x, train_y)

pred_train1 = reg1.predict(train_x)
pred_train2 = reg2.predict(train_x)

pred_val1 = reg1.predict(X_val)
pred_val2 = reg2.predict(X_val)

mse_train1 = mean_squared_error(train_y, pred_train1)
mse_val1 = mean_squared_error(y_val, pred_val1)
mse_train2 = mean_squared_error(train_y, pred_train2)
mse_val2 = mean_squared_error(y_val, pred_val2)

print("1. Lasso\t, train=%.4f, val=%.4f" % (mse_train1, mse_val1))
print("2. Ridge\t, train=%.4f, val=%.4f" % (mse_train2, mse_val2))

1. Lasso	, train=0.0319, val=0.0318
2. Ridge	, train=0.0281, val=0.0280